"""Agent orchestration module for IQFMP.

This module provides LangGraph-based agent orchestration with support for:
- StateGraph state machine pattern
- Checkpoint persistence
- Time-travel debugging
- Conditional routing
- Natural language factor generation
- Factor evaluation
- Strategy assembly
- Backtest optimization
- Risk management
"""

from iqfmp.agents.orchestrator import (
    AgentOrchestrator,
    AgentState,
    Checkpoint,
    CheckpointSaver,
    CompiledGraph,
    ConditionalEdge,
    Edge,
    MemorySaver,
    Node,
    NodeExecutionError,
    OrchestratorConfig,
    OrchestratorError,
    StateGraph,
    StateValidationError,
)
from iqfmp.agents.factor_generation import (
    FactorFamily,
    FactorFieldValidator,
    FactorGenerationAgent,
    FactorGenerationConfig,
    FactorGenerationError,
    FactorPromptTemplate,
    FieldConstraintViolationError,
    FieldValidationResult,
    GeneratedFactor,
    InvalidFactorError,
    SecurityViolationError,
)
from iqfmp.agents.hypothesis_agent import (
    FeedbackAnalyzer,
    Hypothesis,
    HypothesisAgent,
    HypothesisFamily,
    HypothesisGenerator,
    HypothesisStatus,
    HypothesisToCode,
    HYPOTHESIS_TEMPLATES,
)
from iqfmp.agents.evaluation_agent import (
    EvaluationAgentConfig,
    EvaluationAgentError,
    EvaluationAgentResult,
    FactorEvaluationAgent,
    DataValidationError,
    EvaluationTimeoutError,
    create_evaluation_agent,
    evaluate_factors_node,
)
from iqfmp.agents.strategy_agent import (
    CombinationMethod,
    FactorWeight,
    InsufficientFactorsError,
    PortfolioConstruction,
    SignalTransform,
    StrategyAgentError,
    StrategyAssemblyAgent,
    StrategyConfig,
    StrategyResult,
    StrategySignal,
    WeightConstraintError,
    assemble_strategy_node,
    create_strategy_agent,
)
from iqfmp.agents.backtest_agent import (
    BacktestAgentError,
    BacktestConfig,
    BacktestEngine,
    BacktestMetrics,
    BacktestMode,
    BacktestOptimizationAgent,
    InsufficientDataError,
    OptimizationFailedError,
    OptimizationMethod,
    OptimizationResult,
    ParameterSpace,
    TrialResult,
    create_backtest_agent,
    optimize_backtest_node,
)
from iqfmp.agents.risk_agent import (
    ApprovalStatus,
    RiskAgentError,
    RiskAssessment,
    RiskCalculator,
    RiskCategory,
    RiskCheckAgent,
    RiskConfig,
    RiskLevel,
    RiskLimit,
    RiskLimitExceededError,
    RiskMetrics,
    check_risk_node,
    create_risk_agent,
)
from iqfmp.agents.pipeline_builder import (
    PipelineBuilder,
    PipelineConfig,
    build_full_pipeline,
    build_evaluation_only_pipeline,
    build_research_pipeline,
    build_production_pipeline,
)
from iqfmp.agents.model_config import (
    AgentType,
    AgentModelConfig,
    AgentModelRegistry,
    DEFAULT_AGENT_MODELS,
    get_model_registry,
    get_agent_model,
    get_agent_temperature,
)

__all__ = [
    # Orchestrator
    "AgentOrchestrator",
    "AgentState",
    "Checkpoint",
    "CheckpointSaver",
    "CompiledGraph",
    "ConditionalEdge",
    "Edge",
    "MemorySaver",
    "Node",
    "NodeExecutionError",
    "OrchestratorConfig",
    "OrchestratorError",
    "StateGraph",
    "StateValidationError",
    # Factor Generation
    "FactorFamily",
    "FactorFieldValidator",
    "FactorGenerationAgent",
    "FactorGenerationConfig",
    "FactorGenerationError",
    "FactorPromptTemplate",
    "FieldConstraintViolationError",
    "FieldValidationResult",
    "GeneratedFactor",
    "InvalidFactorError",
    "SecurityViolationError",
    # Hypothesis Agent
    "FeedbackAnalyzer",
    "Hypothesis",
    "HypothesisAgent",
    "HypothesisFamily",
    "HypothesisGenerator",
    "HypothesisStatus",
    "HypothesisToCode",
    "HYPOTHESIS_TEMPLATES",
    # Evaluation Agent
    "EvaluationAgentConfig",
    "EvaluationAgentError",
    "EvaluationAgentResult",
    "FactorEvaluationAgent",
    "DataValidationError",
    "EvaluationTimeoutError",
    "create_evaluation_agent",
    "evaluate_factors_node",
    # Strategy Agent
    "CombinationMethod",
    "FactorWeight",
    "InsufficientFactorsError",
    "PortfolioConstruction",
    "SignalTransform",
    "StrategyAgentError",
    "StrategyAssemblyAgent",
    "StrategyConfig",
    "StrategyResult",
    "StrategySignal",
    "WeightConstraintError",
    "assemble_strategy_node",
    "create_strategy_agent",
    # Backtest Agent
    "BacktestAgentError",
    "BacktestConfig",
    "BacktestEngine",
    "BacktestMetrics",
    "BacktestMode",
    "BacktestOptimizationAgent",
    "InsufficientDataError",
    "OptimizationFailedError",
    "OptimizationMethod",
    "OptimizationResult",
    "ParameterSpace",
    "TrialResult",
    "create_backtest_agent",
    "optimize_backtest_node",
    # Risk Agent
    "ApprovalStatus",
    "RiskAgentError",
    "RiskAssessment",
    "RiskCalculator",
    "RiskCategory",
    "RiskCheckAgent",
    "RiskConfig",
    "RiskLevel",
    "RiskLimit",
    "RiskLimitExceededError",
    "RiskMetrics",
    "check_risk_node",
    "create_risk_agent",
    # Pipeline Builder
    "PipelineBuilder",
    "PipelineConfig",
    "build_full_pipeline",
    "build_evaluation_only_pipeline",
    "build_research_pipeline",
    "build_production_pipeline",
    # Model Configuration
    "AgentType",
    "AgentModelConfig",
    "AgentModelRegistry",
    "DEFAULT_AGENT_MODELS",
    "get_model_registry",
    "get_agent_model",
    "get_agent_temperature",
]
